# @package _global_

model:
  name: "abmil_gmu"
  visual_dim: 1024
  text_dim: 1024
  hidden_dim: 256
  dropout_rate: 0.4

training:
  gpu_id: 1
  lr: 5e-4
  weight_decay: 1e-2

# 👇 明确规定单模态的保存路径，强行覆盖主配置
paths:
  output_dir: "${paths.base_data_dir}/Result/FINAL/WSI_Text_Dual"

swanlab:
  enable: True
  api_key: ".."
  project: "GastricCancer_pCR_Prediction"
  workspace: null
  name: "WSI_Text_Dual"
