# @package _global_
model:
  name: "abmil_gmu_tri"
  visual_dim: 1024     # 修改为实际提取的 1024
  text_dim: 1024       # 修改为实际提取的 1024
  ct_dim: 107
  hidden_dim: 256      # 隐藏层可以保持 512 也可以改成 256
  lr: 5e-4
  weight_decay: 1e-2
  dropout_rate: 0.4    # 样本量少，适当调高 Dropout 防过拟合

paths:
  base_data_dir: "/.."
  original_excel_dir: "${paths.base_data_dir}/.."
  feature_dir: "${paths.base_data_dir}/.."
  ct_features_dir: "${paths.base_data_dir}/.."
  split_dir: "${paths.base_data_dir}/.."
  output_dir: "${paths.base_data_dir}/.."

swanlab:
  enable: True
  api_key: ".."
  project: "GastricCancer_pCR_Prediction"
  workspace: null
  name: "TriModal_S1" # 👈 直接在这里控制项目名称
